# Generated by Django 4.2.3 on 2023-07-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Please enter your first name.', max_length=100)),
                ('last_name', models.CharField(help_text='Please enter your last name.', max_length=100)),
                ('company', models.CharField(blank=True, help_text='Please enter your company name (optional).', max_length=200)),
                ('email', models.EmailField(help_text='Please enter a valid email address.', max_length=254)),
                ('phone_number', models.CharField(help_text='Please enter your phone number.', max_length=20)),
                ('source_language', models.CharField(help_text='Please select the source language.', max_length=100)),
                ('target_language', models.CharField(help_text='Please select the target language.', max_length=100)),
                ('additional_languages', models.CharField(blank=True, help_text='If you need to translate to multiple languages, please specify here.', max_length=200)),
                ('translate_to_multiple_languages', models.BooleanField(default=False, help_text='Check this box if you need to translate into multiple languages.')),
                ('certified_translation_needed', models.CharField(choices=[('uscis', 'Yes - Documents for the USCIS, certificates, contracts'), ('non_uscis', 'No - Websites, marketing, e-commerce')], help_text='Select whether you need a certified translation for documents related to the USCIS or other purposes.', max_length=100)),
                ('translation_quality', models.CharField(choices=[('superior', 'Superior - Websites and material for print, as well as legal, financial and medical documents. Higher price.'), ('good', 'Good - Material for internal use and correspondence. Mid-range.'), ('basic', 'Basic - I just need to understand the text. Low price.')], help_text='Select the level of translation quality you require.', max_length=100)),
                ('files_to_translate', models.FileField(help_text='Upload the files you need to be translated.', upload_to='uploads/')),
                ('description', models.TextField(help_text='Provide additional information about your translation request.')),
                ('expedited_service', models.BooleanField(default=False, help_text='Check this box if you need expedited service.')),
                ('discount_code', models.CharField(blank=True, help_text='If you have a discount code, enter it here (optional).', max_length=50)),
                ('terms_and_conditions', models.BooleanField(help_text='Check this box to agree to the terms and conditions.')),
            ],
        ),
    ]
