# Generated by Django 4.2.3 on 2023-07-28 17:53

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfiles',
            name='original_file',
            field=models.FileField(upload_to=app.models.client_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt', 'jpg', 'png', 'jpeg', 'gif']), app.models.file_size]),
        ),
    ]
