# Generated by Django 4.2.3 on 2023-08-01 15:08

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_clientfiles_original_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfiles',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Void', 'Void')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientfiles',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to=app.models.client_processed_directory_path, validators=[app.models.file_size]),
        ),
    ]
