# Generated by Django 4.2.3 on 2023-08-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_clientfiles_status_alter_clientfiles_processed_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('void', 'Void')], default='Pending', max_length=20),
        ),
    ]
