# Generated by Django 4.2.3 on 2023-07-26 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_inprogressrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inprogressrequest',
            old_name='in_progress_date',
            new_name='in_progress_at',
        ),
        migrations.RemoveField(
            model_name='inprogressrequest',
            name='in_progress_notes',
        ),
        migrations.AlterField(
            model_name='inprogressrequest',
            name='translation_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='in_progress', to='app.translationrequest'),
        ),
    ]
