# Generated by Django 4.2.3 on 2023-08-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_translationrequest_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientFiles',
            new_name='ClientFile',
        ),
    ]
