# Generated by Django 4.2.3 on 2023-07-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_in_progress_date_inprogressrequest_in_progress_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationrequest',
            name='additional_languages',
        ),
        migrations.RemoveField(
            model_name='translationrequest',
            name='company',
        ),
        migrations.RemoveField(
            model_name='translationrequest',
            name='expedited_service',
        ),
        migrations.RemoveField(
            model_name='translationrequest',
            name='translate_to_multiple_languages',
        ),
    ]
