# Generated by Django 4.2.3 on 2023-08-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_clientfiles_clientfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfile',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='content',
            field=models.TextField(default='', verbose_name='Additional information'),
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='source_language',
            field=models.CharField(choices=[('French', 'French'), ('Haitian Creole', 'Haitian Creole'), ('English', 'English'), ('Spanish', 'Spanish')], default='Unspecified', max_length=50),
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='target_language',
            field=models.CharField(choices=[('French', 'French'), ('Haitian Creole', 'Haitian Creole'), ('English', 'English'), ('Spanish', 'Spanish')], default='Unspecified', max_length=50),
        ),
    ]
