# Generated by Django 4.2.3 on 2023-07-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_translationrequest_additional_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationrequest',
            name='source_language',
            field=models.CharField(choices=[('French', 'French'), ('Haitian Creole', 'Haitian Creole'), ('English', 'English'), ('Spanish', 'Spanish')], help_text='Choose the language of the document.', max_length=100),
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='target_language',
            field=models.CharField(choices=[('French', 'French'), ('Haitian Creole', 'Haitian Creole'), ('English', 'English'), ('Spanish', 'Spanish')], help_text='Choose your destination language', max_length=100),
        ),
    ]
