# Generated by Django 4.2.3 on 2023-07-26 23:01

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_translationrequest_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationrequest',
            name='files_to_translate',
            field=models.FileField(help_text='Upload the files you need to be translated.', upload_to='uploads/', validators=[app.models.TranslationRequest.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['.pdf', '.doc', '.docx', '.txt']), app.models.TranslationRequest.validate_no_executable]),
        ),
        migrations.DeleteModel(
            name='InProgressRequest',
        ),
    ]
