# Generated by Django 4.2.3 on 2023-07-27 17:40

import app.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_translationrequest_files_to_translate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('term_condition', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='files_to_translate',
            field=models.FileField(help_text='Upload the files you need to be translated.', upload_to='uploads/request/', validators=[app.models.TranslationRequest.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['.pdf', '.doc', '.docx', '.txt']), app.models.TranslationRequest.validate_no_executable, app.models.TranslationRequest.validate_max_files]),
        ),
        migrations.CreateModel(
            name='ClientFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app.models.client_directory_path, validators=[app.models.file_size])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_files', to='app.clientinfo')),
            ],
        ),
    ]
